default: &default
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  primary:
    <<: *default
    adapter: mysql2
    encoding: utf8mb4
    database: <%= ENV.fetch("DB_NAME") { "tebook_local_db" } %>
    username: <%= ENV.fetch("DB_USERNAME") { "expressativo" } %>
    password: <%= ENV.fetch("DB_PASSWORD") { "expressativo" } %>
    host: <%= ENV.fetch("DB_HOST") { "127.0.0.1" } %>
    port: <%= ENV.fetch("DB_PORT") { 3306 } %>

  queue:
    <<: *default
    adapter: mysql2
    encoding: utf8mb4
    database: <%= ENV.fetch("DB_NAME") { "tebook_local_db" } %>
    username: <%= ENV.fetch("DB_USERNAME") { "expressativo" } %>
    password: <%= ENV.fetch("DB_PASSWORD") { "expressativo" } %>
    host: <%= ENV.fetch("DB_HOST") { "127.0.0.1" } %>
    port: <%= ENV.fetch("DB_PORT") { 3306 } %>
    schema_dump: queue_schema.rb
    migrations_paths: db/queue_migrate


test:
  primary:
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    timeout: 5000

  queue:
    <<: *default
    adapter: mysql2
    encoding: utf8mb4
    database: <%= ENV.fetch("DB_NAME") { "tebook_test_db" } %>
    username: <%= ENV.fetch("DB_USERNAME") { "expressativo" } %>
    password: <%= ENV.fetch("DB_PASSWORD") { "expressativo" } %>
    host: <%= ENV.fetch("DB_HOST") { "127.0.0.1" } %>
    port: <%= ENV.fetch("DB_PORT") { 3306 } %>
    schema_dump: queue_schema.rb
    migrations_paths: db/queue_migrate


production:
  primary:
    adapter: mysql2
    encoding: utf8mb4
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    database: <%= ENV.fetch("DB_NAME") { "tebook_local_db" } %>
    username: <%= ENV.fetch("DB_USERNAME") { "expressativo" } %>
    password: <%= ENV.fetch("DB_PASSWORD") { "expressativo" } %>
    host: <%= ENV.fetch("DB_HOST") { "localhost" } %>
    port: <%= ENV.fetch("DB_PORT") { 3306 } %>


  cable:
    adapter: mysql2
    encoding: utf8mb4
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    database: <%= ENV.fetch("DB_NAME") { "tebook_local_db" } %>
    username: <%= ENV.fetch("DB_USERNAME") { "expressativo" } %>
    password: <%= ENV.fetch("DB_PASSWORD") { "expressativo" } %>
    host: <%= ENV.fetch("DB_HOST") { "localhost" } %>
    port: <%= ENV.fetch("DB_PORT") { 3306 } %>

  queue:
    adapter: mysql2
    encoding: utf8mb4
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    database: <%= ENV.fetch("DB_NAME") { "tebook_local_db" } %>
    username: <%= ENV.fetch("DB_USERNAME") { "expressativo" } %>
    password: <%= ENV.fetch("DB_PASSWORD") { "expressativo" } %>
    host: <%= ENV.fetch("DB_HOST") { "localhost" } %>
    port: <%= ENV.fetch("DB_PORT") { 3306 } %>
    schema_dump: queue_schema.rb
    migrations_paths: db/queue_migrate

  cache:
    adapter: mysql2
    encoding: utf8mb4
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    database: <%= ENV.fetch("DB_NAME") { "tebook_local_db" } %>
    username: <%= ENV.fetch("DB_USERNAME") { "expressativo" } %>
    password: <%= ENV.fetch("DB_PASSWORD") { "expressativo" } %>
    host: <%= ENV.fetch("DB_HOST") { "localhost" } %>
    port: <%= ENV.fetch("DB_PORT") { 3306 } %>

